# Generated by Django 6.1.1 on 2026-09-23 14:15

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('jsearch', 'JSearch (LinkedIn/Indeed/Glassdoor)'), ('adzuna', 'Adzuna'), ('internshala', 'Internshala'), ('manual', 'Manual entry')], max_length=20)),
                ('source_url', models.URLField(max_length=500)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
