# Generated by Django 6.1.1 on 2026-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='communication_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='filler_word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='words_per_minute',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
